apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-kafka-cluster
  namespace: kafka
spec:
  # Enable Kafka Exporter
  kafkaExporter:
    groupRegex: .* # You can filter the consumer grouops
    topicRegex: .* # and topics to export with a regex
    template:
      pod:
        metadata:
          labels:
            kafka-metrics: 'true'
  kafka:
    version: 3.8.0  # Updated Kafka version
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "3.8"  # Match with the updated version
    storage:
      type: ephemeral  # Keep this as ephemeral, no size needed
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral  # Keep this as ephemeral, no size needed
  entityOperator:
    topicOperator: {}
    userOperator: {}
