apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaCluster
metadata:
  name: my-kafka-cluster
spec:
  kafka:
    replicas: 3
    listeners:
      plain:
        port: 9092
        type: internal
      plain-external:
        port: 9092
        type: external
    config:
      offsets.topic.replication.factor: 3
  zookeeper:
    replicas: 3