global:
  scrape_interval: 5s
  evaluation_interval: 15s
  external_labels:
    monitor: 'my-kafka-cluster'

scrape_configs:
- job_name: kafka
  static_configs:
  - targets: ['my-kafka-cluster-kafka-bootstrap:9092']