apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-kafka-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strimzi-kafka-operator
  template:
    metadata:
      labels:
        app: strimzi-kafka-operator
    spec:
      containers:
      - name: strimzi-kafka-operator
        image: strimzi/strimzi-kafka-operator:latest
        args:
        - --config-file=/etc/strimzi/kafka-operator.yaml
        volumeMounts:
        - name: strimzi-config
          mountPath: /etc/strimzi
      volumes:
      - name: strimzi-config
        configMap:
          name: strimzi-kafka-operator-config