apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 3.8.0
    replicas: 3
    listeners:
      - name: tls
        port: 9093
        type: loadbalancer
        tls: true
        authentication:
          type: tls
    authorization:
      type: simple  # Ensure 'simple' authorization is correctly set
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      authorizer.class.name: kafka.security.authorizer.AclAuthorizer  # Set this for ACL support
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
