apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: my-connect-cluster
  namespace: strimzi
spec:
  replicas: 1
  bootstrapServers: my-kafka-cluster-kafka-bootstrap:9092
  config:
    group.id: "connect-cluster"
    offset.storage.topic: "connect-cluster-offsets"
    config.storage.topic: "connect-cluster-configs"
    status.storage.topic: "connect-cluster-status"
    plugin.path: "/opt/kafka/external-configuration/plugins"  # Kafka Connect plugin path
  image: strimzi/kafka-connect:latest
  template:
    pod:
      securityContext:
        runAsUser: 0  # Run as root to grant necessary permissions
  externalConfiguration:
    volumes:
      - name: plugins
        configMap:
          name: my-connector-plugins  # Use a ConfigMap to store the connectors
