apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: my-connect-cluster
  namespace: strimzi
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  image: junaidajdocker/my-custom-kafka-connect:latest
  replicas: 1
  bootstrapServers: my-kafka-cluster-kafka-bootstrap:9092
  config:
    group.id: "connect-cluster"
    offset.storage.topic: "connect-cluster-offsets"
    config.storage.topic: "connect-cluster-configs"
    status.storage.topic: "connect-cluster-status"
    plugin.path: "/opt/kafka/plugins"
  # Add security context to ensure UID alignment with container settings
  template:
    pod:
      securityContext:
        runAsUser: 1001
        runAsGroup: 0
        fsGroup: 0
