apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: kafka-connect
  namespace: kafka
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  bootstrapServers: my-kafka-cluster-kafka-bootstrap:9092
  version: 3.7.0
  replicas: 1
  image: junaidajdocker/junaid-confluentinc-kafka-connect-jdbc-10.8.0:latest
  config:
    group.id: my-connect-cluster
    offset.storage.topic: my-connect-cluster-offsets
    config.storage.topic: my-connect-cluster-configs
    status.storage.topic: my-connect-cluster-status
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.storage.StringConverter
    #key.converter: org.apache.kafka.connect.json.JsonConverter
    #value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: true
    value.converter.schemas.enable: true
    config.storage.replication.factor: 3
    offset.storage.replication.factor: 3
    status.storage.replication.factor: 3
    plugin.path: /opt/kafka/plugins  # Add this line to specify the plugin path
