FROM quay.io/strimzi/kafka:0.43.0-kafka-3.7.0
USER root
# Add additional plugins or configurations here
ADD confluentinc-kafka-connect-jdbc-10.8.0 /opt/kafka/plugins/confluentinc-kafka-connect-jdbc-10.8.0
USER 1001