apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: kafka-cluster-2-node-pool
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster-2
spec:
  replicas: 3
  roles:
    - broker
    - controller
  storage:
    type: ephemeral