apiVersion: v1
kind: Pod
metadata:
  name: postgres-test
  namespace: kafka
spec:
  containers:
    - name: postgres-client
      image: postgres:13  # Official PostgreSQL image with client tools
      command: ["sleep", "3600"]  # Keep the pod running
