apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: postgres-users  # Name of the Kafka topic
  namespace: strimzi    # Namespace where Strimzi is installed
  labels:
    strimzi.io/cluster: my-kafka-cluster  # The Kafka cluster that will host this topic
spec:
  partitions: 3          # Number of partitions
  replicas: 1            # Number of replicas
  config:
    retention.ms: 604800000  # Example configuration (1 week retention)
    cleanup.policy: delete   # Policy for log cleanup
